apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: container-demo
  template:
    metadata:
      labels:
        app: container-demo
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: container-demo
          image: registry.local:5000/sample-app-container:A954872
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
      nodeSelector:
        type: container
