apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-webserver
  template:
    metadata:
      labels:
        app: container-webserver
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: container-webserver
          image: registry.local:5000/sample-app-container:849a371
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
      nodeSelector:
        container: "true"
