apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasmtime
  template:
    metadata:
      labels:
        app: wasmtime
    spec:
      runtimeClassName: wasmtime
      terminationGracePeriodSeconds: 0
      containers:
        - name: wasmtime
          image: registry.local:5000/sample-app-wasm:c38135b
          command: ["main.wasm"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
      nodeSelector:
        type: wasm
