apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-with-key
  annotations:
    policies.kyverno.io/title: Verify Image with cosign and key
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.0
    policies.kyverno.io/description: >-
      Verifies that only signed images can be deployed. Only signatures that can be decrypted with the submitted public key are allowed.
      This gives you control over what kind of signing keys are allowed.
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-image-with-key
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "*"
        mutateDigest: true
        attestors:
        - entries:
          - keys:
              secret:
                # Example: use existing secret
                name: cosign-public
                namespace: kyverno
