name: Build, Push and Sign Container Image

on:
  push:
    branches:
      - "main"
    paths:
      - "containerdays-2025/demo/sample-app/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: relusc/cd-2025-sample-app
  WORKDIR: containerdays-2025/demo/sample-app

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      id-token: write # For OIDC and Cosign

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.5.3" # latest version (01.08.2025)

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign container image with Cosign
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "Signing image with digest: ${DIGEST}"
          cosign sign --yes "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${DIGEST}"

      - name: Verify signature
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "Verifying signature..."
          cosign verify \
            --certificate-identity-regexp="https://github.com/${{ github.repository }}" \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${DIGEST}"
